# Generated by Django 4.1.13 on 2023-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docs_crawler", "0002_alter_preferences_documentation_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="autogenerate_block",
            field=models.BooleanField(
                default=True,
                help_text="Autogenerate blocks from the documentation. If unchecked, it will use blocks child of this page.",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="If no title is provided, it will use the title of the anchor on documentation page.",
                max_length=512,
                null=True,
            ),
        ),
    ]
